### ISSUE TITLE
[RPR] Reaping skills individual

### ISSUE THREAD

**Issue by Sissyhime** [Nik-Potokar/XIVSlothCombo#1563] opened 2024-07-19 10:30 UTC
I know this is probably niche to ask for, but I preferred it when I could use the Reaping skills on my main button without needing to add Enshroud to the button as well. I want Enshroud as its own button specifically to avoid overusing it. Feels like consolidation went a bit too hard in some places.

**Comment by Kagekazu** [comment] 2024-07-19 10:32
duplicate of #1531

**Closed** 2024-07-23 07:22 UTC
