### ISSUE TITLE
[RDM] Scorch+Resolution Feature needed for AoE Combo

### ISSUE THREAD

**Issue by Serfrost** [Nik-Potokar/XIVSlothCombo#181] opened 2022-01-25 14:30 UTC
I've been enjoying the other options in their entirety so far, it's nice to be able to pay attention to mechanics for once so thank you for that. However, during trash pulls, the AoE combo does not resolve in Scorch + Resolution.

Verthunder II/Veraero II --> Impact --> 
(60+ Mana) --> Enchanted Moulinet x3 -->
Verflare/Verholy --> Scorch --> Resolution

**Currently this chain ends at Verflare/Verholy** and goes back to Verthunder II/Veraero II

Ideally Verthunder II, Veraero II, and Enchanted Moulinet would be changed to Verflare/Verholy --> Scorch --> Resolution ... and presently, Enchanted Moulinet does not change skills after 3 casts either, which is rather detrimental.

This has resulted in my Mana Stacks being reset quite a few times now, so if this could be considered it would be amazing.

**Comment by Nik-Potokar** [comment] 2022-01-25 15:34
Sure thing it can be added. I will try and add it tonight if I get some free time before raid if not il try and add it asap

**Comment by Serfrost** [comment] 2022-01-25 15:57
Very much appreciated.  I feel it's just about the only thing RDM could need at this point.

**Comment by Nik-Potokar** [comment] 2022-01-25 15:59
Yeah I get you it will be a good addition. I just havent played rdm since start of shb so haven't noticed it missing lol but will add asap

**Comment by Nik-Potokar** [comment] 2022-01-25 20:28
So currently Enchanted Moulinet/SmartCastFeature will change into all the finisher combos but its still a separate button from the smart cast feature. Im currently looking into adding all on one button like the additional testing feature "Simple Redmage" that ive added that combines both ranged and melee combo single target combos

**Comment by Serfrost** [comment] 2022-01-26 01:57
I'm fine with pressing Moulinet separately. That makes it the same as the Melee combo. I don't want it *too* simplified (one button for everything). However, thank you, I'll give it a try when possible and let you know how it goes.

**Comment by Serfrost** [comment] 2022-01-26 02:50
I tried out the Simple Red Mage Single Target option and it seems that if you're over-capped on Mana (over 50,) you will keep using Reposte.  For example when you're at 90+ Mana the chain becomes..

Reposte --> Reposte --> Reposte --> (3 Mana stacks) --> 
Zwercchau (wasted) --> Redoublement (wasted) --> 
Verflare/Verholy --> Scorch --> Resolution

When this gets fixed, that feature will work nicely.  Well done.

I also tested the Simple Red Mage AoE option and this doesn't have the same issue, but that may be because it takes 60 Mana in order to facilitate using Moulinet 3 times.  

Have you added any failsafe checks for when users use Manafication at any point in time in order to make use of its Damage Buff during certain situations?  As this may conflict with a lot of the logic, especially seeing how Simple Single Target has the issue with overcapping.

**Comment by Nik-Potokar** [comment] 2022-01-26 08:15
First of all thank you for the detailed feedback and I'm glad that requested feature is working as intended.

1. Yes that is an oversight I made yesterday when doing my quick tests I never tried going above 60mana so I have a fix for this coming later today.

2. It does prioritize melee combo over everything if it meets the mana and melee requirements but the issue is currently there is a small delay with the position calculation so il see if I can fix that delay.

3. Will add a check so it makes sure to always use dualcasts/swiftcast before continuing to melee combo.

4. This is something I haven't tested at all but does makes sense that it would be broken and I will look into it more today.

I haven't added any failsafes yet but that will be coming soon.

**Comment by Serfrost** [comment] 2022-01-26 09:40
1. I had figured that was the case. No biggie, but I wanted to have these written down so you can refer back to it if needed.  You did say this was in testing afterall.

2. You're correct, it's the delay that is the problem. It lasts roughly half a second, so any time you use Corps-a-Corps to engauge, or even walk to the the target, the delay is too significant and will not change the skill before you're already pressing the button (resulting in hard-casting the range skill instead.)

3. Appreciated.  However, please be wary of Swiftcast accidentally taking priority during a Melee combo (resulting in the Melee turning into Range/AoE, eating your Mana Stacks. i.e. If you need to Swiftcast Raise or if you had used Swiftcast on accident/too early.  I don't know if this could happen but I figured I would bring that possibility up.

4. Would be nice to get this fixed since mob groups tend to break down quickly and not all at the same time.

As for the failsafes, just glad you're thinking about them.  I will test any changes you make since I plan to be using RDM a lot in the coming weeks.

**Comment by Multidayz** [comment] 2022-02-01 02:04
Just wanted to chime in, the melee combo portion was working yesterday but after the update today it appears to no longer do any of the melee portions using the smart single target feature or any other combination.
Not sure how else I can help except I am on version 3.0.1.6
Thank you for the help!

**Comment by Serfrost** [comment] 2022-02-01 20:07
@Nik-Potokar I can confirm that pretty much everything broke after I updated today.

**Comment by Multidayz** [comment] 2022-02-02 17:07
Further inspection, it looks like the push that changed this removed several hundred lines of code in it. Is there a way in the interim I can just apply the old RDM.cs file?

**Comment by Nik-Potokar** [comment] 2022-02-02 17:40
So to clarify i have removed the all in one feature that combined smartcast + melee combos due to the delay for checking your position since that was just too long and would 80% of time time result in a GCD delay especially if you would dash in.

I can re-add the feature but its just not in a optimal state due to that atm.

**Comment by Multidayz** [comment] 2022-02-02 17:44
@Nik-Potokar I would totally love it as an option. I found a work around that compensated for it using an ingame macro where the bottom of it I would just throw in some "Jolt" so it wouldn't be completely wasted. For me I know these won't be 100% of real skill but if I'm pumping 80%+ it's good enough for my playstyle.
Thank you again for your time on this.

**Comment by Nik-Potokar** [comment] 2022-02-02 17:49
@Multidayz Sure then will re-add it in a few min

**Comment by Multidayz** [comment] 2022-02-03 20:00
It's working back to the way it was, had a blast playing it last night. Thank you.

**Closed** 2022-02-08 07:55 UTC

**Comment by Serfrost** [comment] 2022-02-12 00:41
> So to clarify i have removed the all in one feature that combined smartcast + melee combos due to the delay for checking your position since that was just too long and would 80% of time time result in a GCD delay especially if you would dash in.
> 
> I can re-add the feature but its just not in a optimal state due to that atm.

Regarding this, I think a quick fix would be to:
- Corps-a-Corps -> Check current Mana -> If Mana is sufficient ->
- Swap to Melee combo regardless of distance -> Begin melee range checks
 
Rather than check if you're in Melee range, just check the mana immediately after Corps-a-Corps is cast. After that you can begin checking for Melee range (in case you didn't want to start Melee combos yet,) as you can just walk out of range.  This should mitigate the problem with having a delay.

There are still some sync issues going between AoE Melee and Single Target Melee. (If I use 1 or 2 AoE Melee attacks, Single Target Melee is still stuck on Enchanted Riposte instead of going to Enchanted Zwerchhau or Enchanted Redoublement (respectively)

Lastly, Melee Range is still overriding Dual Cast, so hopefully that can get resolved.  I'll be keeping an eye on updates.
