### ISSUE TITLE
[SAM] Iaijutsu spam while moving.

### ISSUE THREAD

**Issue by Soltheron** [Nik-Potokar/XIVSlothCombo#770] opened 2022-05-31 04:05 UTC
Turning on the "Iaijutsu while not moving" options doesn't truly work as it just spams back and forth between, for example, Tenka Goken and Fuga at an insane speed. Whenever I hit the button it just tries to do the Iaijutsu anyway even if I'm moving.

**Comment by Taurenkey** [comment] 2022-06-03 17:54
Can I ask if you play with mouse & keyboard or on a controller? Or if you're running multiple combo forks at the same time? It's just that I can't replicate it on this end and the only things I can think of is either you have a hardware defect such as joystick drift which might be nudging your character ever so slightly all the time or you have another combo fork enabled which is trying to compete for the same ability slot.

**Comment by GibXIV** [comment] 2022-06-03 22:05
I tried to replicate this at different levels and with different settings but could not reproduce.
@Soltheron please add more information; at what level, with what input, have you tried reslotting the ability on your bar and can you do a /scombo debug and add the file in here.

**Comment by Taurenkey** [comment] 2022-06-22 10:56
User on Discord has reported a similar sounding issue and managed to find success in preventing it by disabling a tweak in SimpleTweaks called Duplicate Keybind Hint Between Hotbars. If this can be confirmed as a definitive cause we can close this issue, otherwise its likely to be attributed to similar features in other plugins.

**Comment by k-kz** [comment] 2022-06-25 15:03
Closing for now. Please reopen if the problem reoccurs.

**Closed by k-kz** 2022-06-25 15:03 UTC
Labels: Bug, More Info Needed
