### ISSUE TITLE
[RPR] Shadow of Death Option not working while in combat

### ISSUE THREAD

**Issue by inu-goro** [Nik-Potokar/XIVSlothCombo#1665] opened 2024-08-04 03:26 UTC
I have the following settings enabled:

Adanced Mode: Single Target
 Shadow of Death Option (6 second - 1%)
 Gibbet and Gallows Option
Advanced Mode: AoE
 Whorl of Death Option (1%)
 Guillotine Option

While not in combat, Shadow of Death Option works fine ("Slice" is replaced with "Shadow of Death" when I target an enemy).
But once I start the combat in dungeons, the basic combo works fine, but "Shadow of Death" does not appear during the rotation (When I try to attack the enemy with no death design, the rotation starts with "Slice").

This only happens while in combat.

**Comment by doh666** [comment] 2024-08-04 22:08
I am seeing something similar. when enshrouded and shadow of death falls off or hits 6 seconds it doesn't reapply and strait up stops reaping combo and slice combo until i hit whorl of death to reapply deaths design

**Comment by Kagekazu** [comment] 2024-08-04 22:10
duplicate of #1601

**Closed** 2024-08-10 06:10 UTC
