### ISSUE TITLE
[MCH] Problem with Scaling down in General

### ISSUE THREAD

**Issue by Dismes** [Nik-Potokar/XIVSlothCombo#320] opened 2022-03-30 03:13 UTC
So I am leveling but here are a few problems I have found with playing machinist.

 Simple Machinist doesn't work and 50 and under I believe. 
Simple Machinist doesn't use  Drill on CD
(Heated) Shot Combo doesn't work properly once you get heated Clean shot, the 1-2-3 does work but the rest of the combo like Drill, heatblast, ricochet & Gauss break.  This also break if you use Hypercharge before you are level 35. 

![image](https://user-images.githubusercontent.com/19319649/160743895-43bc4739-8089-44d9-a7e9-1f0ced78d9e0.png)
![image](https://user-images.githubusercontent.com/19319649/160743915-d192ff6a-be58-42ff-b819-16516df155a3.png)

**Comment by Taurenkey** [comment] 2022-03-30 06:40
Hi, just a quick few questions:

For drill not being used on CD, is it using drill _at all_? Looking at the code the priority on drill isn't the highest so there's a chance it'll be a few GCDs before it gets to it.

Also looking at your settings, you have other presets enabled. Simple features like this tends to clash with other features. @augporto any chance you can throw up some conflicting combo attributes on it just to make the end-user experience better? @Dismes try turning everything except the simple features off and try again. Also you may need to reslot Split Shot to your hotbar to get it to actually kick in.

**Comment by Dismes** [comment] 2022-03-30 07:32
I tried disabling everything but simple and  resloting the skills and it seems to solve most of the problem, I think the conflicting setting was messing with it.  and for drill, it coming out a few GCDs late, rather in on CD

**Comment by Dismes** [comment] 2022-03-30 07:40
The other bug I found was the same as 
https://github.com/Nik-Potokar/XIVSlothCombo/issues/281
the TL;DR is using (heated) Shot Combo with PVP options on, seems to make it not work

**Comment by Taurenkey** [comment] 2022-03-30 08:04
@Dismes Which PvP options specifically? I know there's only 2 but from looking at the code there shouldn't be any interference between the 2 modules. There's no PvP code in the PvE combos so how much does it not work? Like, at all? Only some?

**Comment by Dismes** [comment] 2022-03-30 08:12
So went back into Bardam's Mettle at level 66 with these setting
![image](https://user-images.githubusercontent.com/19319649/160783643-1231d525-9e1c-489d-bf16-54403d4a221b.png)

it works with these setting but enabling WildfireBlankFeature seems to break it
With WildfireBlankFeature on, the basic 1-2-3 works but doesn't update the icon, nor does Drill, heatblast, ricochet & Gauss break get added on to the combo

**Comment by Taurenkey** [comment] 2022-03-30 08:27
Looking at the `WildfireBlankFeature` (and the other PvP combo too, I think they both do the same thing) I think I can see where the issue is. 

If I'm right, I'll have it fixed with tonight's update hopefully, but for now turn off both those PvP combos when using any features. Thankfully it should only involves tweaking two lines, but I'm gonna raise what happened in it as a word of warning for other contributors and I'll look for any other instances of this problem to try and fix them elsewhere in the plugin.

**Comment by augporto** [comment] 2022-03-30 11:16
@Dismes Yes it was a miss on my part sorry , i should have marked simple with `conflict with other ST options` . 

To use `Simple` features you have to disable all other ST options , just leave simple machinist and its its child options marked.

It does not conflict with the AOE features though , you can leave `Spreadshot/Scattergun Heat , +Bioblaster` and its child options marked , they should work ok.

**Closed** 2022-04-02 04:28 UTC
Labels: bug
