### ISSUE TITLE
Dnc overcapping resources

### ISSUE THREAD

**Issue by Djota22** [Nik-Potokar/XIVSlothCombo#771] opened 2022-06-01 03:02 UTC
Anyone else having problem with dnc overcapping feathers and esprit because apparently now its prioritizing the combo actions on simple dancer, so i can be at 100 esprit it will first cast any proc i have for a combo and only then use saber dance, also when getting the 4th feather it will only be spent on next gcd, i didnt have this problem before so not sure if its only me.

**Comment by k-kz** [comment] 2022-06-01 19:17
Can you go in-game and type `/scombo debug` into chat, then paste the relevant DNC portion (or whole file, if that's easier) please? That way we can use your enabled features and attempt to replicate the issue.
Thanks!

**Comment by Taurenkey** [comment] 2022-06-03 17:08
Having reviewed the code for Simple Single Target Dancer, the _only_ abilities that are prioritised above Fan Dance when feathers are capped are Standard Step, Technical Step, Head Graze (for interrupts if enabled), Devilment and Flourish. However, feathers will only be spent as an oGCD and not _as_ a GCD so if you have bad ping then this might make it harder for you to weave them.

As for Saber Dance, it's literally the first GCD it checks for after Standard Step & Technical Step and it's set to kick in the instant you're at 85 espirit or above, regardless of options. As such, from reviewing the code and testing it myself in game just to make sure, I can see no reason for Simple Single Target Dancer to not spend these resources properly. The only explanations I could have is if you're using other plugins that _could_ be interfering with our plugin (such as other combo forks) or if you've not updated Sloth in a really long time. 

Without further information, I am unable to replicate this bug.

**Comment by GibXIV** [comment] 2022-06-03 22:08
I tried to replicate this for an hour on dummies and in scaled content at different levels with a few different settings, could not reproduce your findings.
@Djota22 please add aditional info as requested above

**Comment by k-kz** [comment] 2022-06-11 23:45
Unable to replicate - closing for now. Let us know if this issue recurs

**Closed by k-kz** 2022-06-11 23:45 UTC
Labels: Bug, More Info Needed
