### ISSUE TITLE
All Jobs PvP items applying in PvE instance

### ISSUE THREAD

**Issue by Wizard1134** [Nik-Potokar/XIVSlothCombo#599] opened 2022-04-27 02:54 UTC
Doing the Summoner quest Rescue the Summoners and now the PvP debuff/heal abilities are being pushed to hotbars.

On version 3.0.12.2

[Screenshot](https://i.imgur.com/z2gHS8d.jpg)

**Comment by k-kz** [comment] 2022-04-27 02:59
Not entirely sure what we can do about this one at first glance.

The issue is occurring because that instanced quest is taking place on "Seal Rock" - which is traditionally a PvP map.
Our PvP global features check whether you're on a PvP map to activate.

I'm not sure how we'll get around this without *significant* expansion of our current PvP-check methods.
For the time being, please disable the features to carry on as normal. Apologies!

**Comment by k-kz** [comment] 2022-04-28 17:35
Addressed in #604

**Closed by k-kz** 2022-04-28 17:35 UTC
Labels: Bug, Consideration Needed
