### ISSUE TITLE
RPR - Advanced AoE Enshroud attacks only triggering when Automatic Enshroud is also active

### ISSUE THREAD

**Issue by Wild-Carrot** [Nik-Potokar/XIVSlothCombo#1644] opened 2024-07-30 13:22 UTC
**Class/Job:** Reaper
**Feature:** Adv Mode - AoE, Enshroud Option

**Issue:**
When using Reaper's AoE without the Enshroud option enabled for automatic use, options such as Grim Reaping, Lemure's Scythe, Communio, and probably others do not take effect. Instead, Spinning Scythe remains Spinning Scythe and unusable (during Enshroud).

Enabling the automatic enshroud options allows the other options to start working. They aren't listed as suboptions to Enshroud, so I don't think this is intended behavior.

**Comment by Kagekazu** [comment] 2024-07-30 13:32
this is fixed in PR #1587 

where its split as intended

**Comment by Wild-Carrot** [comment] 2024-07-30 13:36
Ah, I see. I should've searched better. I knew there were some Reaper issues, but somehow missed that this was reported.

**Comment by Kagekazu** [comment] 2024-07-31 08:16
You are correct, i forgot to remove an enshroud check when decoupling the 2.

Will be fixed in my next commit.( Also if u add the enshroud buttons to AoE, i do recommend u add Communio for the AoE, since it also does AoE Damage)

**Closed** 2024-08-10 06:10 UTC
