### ISSUE TITLE
[DNC] Simple Single Target to another button

### ISSUE THREAD

**Issue by johnmarklg** [Nik-Potokar/XIVSlothCombo#571] opened 2022-04-24 17:54 UTC
Hello! Is it possible to change the button to another like say, Saber Dance? That way in situations when we need to hold our bursts we can still do normal 1-2 combos. Thank you! Same for Bard as well, maybe with the separate Straight Shot/Refulgent Arrow button.

**Comment by k-kz** [comment] 2022-04-24 17:56
Duplicate of #415

**Closed by k-kz** 2022-04-24 17:56 UTC
