### ISSUE TITLE
[PLD] Royal Authority Combo

### ISSUE THREAD

**Issue by Ideali5t** [Nik-Potokar/XIVSlothCombo#282] opened 2022-03-05 01:23 UTC
When I use the Royal Authority Combo option, royal authority appears as rage of halone. This is at level 90.

**Comment by Iaotle** [comment] 2022-04-02 04:18
Duplicate of closed issue https://github.com/Nik-Potokar/XIVSlothCombo/issues/232, was never fixed.

**Closed by Iaotle** 2022-04-02 04:18 UTC
Labels: bug
