### ISSUE TITLE
[BRD] Song rotation

### ISSUE THREAD

**Issue by SugarFreeCoffee56** [Nik-Potokar/XIVSlothCombo#1518] opened 2024-07-12 09:23 UTC
Hello, 
I could not find any infos on this but it appears the song rotation is the same as it was in EW (Mage's Ballad ends at 12sec) instead of the new standard 3-3-12 rotation.
I have tried disabling auto-song in Simple Bard but it messes up with the opener too much

**Comment by NebulousByte** [comment] 2024-07-12 11:19
Overlooked this. Should be fixed soon.

**Comment by NebulousByte** [comment] 2024-07-12 12:08
Fix is ready to be merged for single target. I haven't changed the logic for AoE, however. That might want to be changed in the future (I don't know).

**Comment by skolosk** [comment] 2024-07-12 12:12
For single target and aoe it is not working as it used to.  in full single button rotations it would drop songs by ending them too soon leaving them all on cooldown. it would use radiant finale without BV and sometimes with. ignores raging strikes and barrage a lot of the time - will post a separate issue for this

**Comment by NebulousByte** [comment] 2024-07-12 12:26
I'm not sure what you mean by too soon. In the current release (not the fix mentioned above), songs are in the wrong order of when they end. The fix is waiting to be merged. In that fix, it works on 3-3-12 "Standard." That is, songs _will_ end early. It's by design. You start with the Wanderer's Minute, 3 seconds from the end you'll go to Mage's Ballad, then 3 seconds from the end you'll go to Army's Paeon. When there's less than 12 seconds left on Army's Paeon, you go back to the Wanderer's Minute.

For AoE, the logic hasn't changed from the old version. There is only one timer check for <12 seconds.

**Comment by skolosk** [comment] 2024-07-12 12:29
Too soon meaning - I would sit there songless with all songs on cooldown.

**Comment by skolosk** [comment] 2024-07-12 12:37
So they're not supposed to match in sloth?

**Comment by NebulousByte** [comment] 2024-07-12 12:53
Not currently. It's always just been 12-12-12, so there's a lot of overlap. E.g. if you're in a dungeon and you've spent all your songs on a trash pull, you're likely going to be songless with songs on cooldown going into a boss fight, or you're in the middle of a boss fight and you swap to AoE to deal with adds. It's always been like this. Though I can certainly change it so they work on the same timings.

**Comment by skolosk** [comment] 2024-07-12 12:56
I never used/heard of 12-12-12 in dungeons. I heard of dropping WM and starting with ballad, but now with PP being aoe and barrage new ability, everything should line up. single target and aoe. Part of why they did what they did in DT was to fix that discrepancy in dungeons.

**Comment by NebulousByte** [comment] 2024-07-12 13:42
Will add in the logic to AoE that ST has for songs and add in PP. Will make a new PR later once tested.

**Comment by qnesp1987** [comment] 2024-07-13 05:38
new standard is 3-3-9 and AoE = sing;e target. Wanderer's Minuet is now the strongest song for AoE.  It isnt  3 -3-12

also AoE has never been 12-12-12 - that would mean a brd would deliberately have to plan a rotation that would leave them songless. On the balance BRD resources t says  3-3-9

Thank you

**Comment by NebulousByte** [comment] 2024-07-13 09:47
> also AoE has never been 12-12-12
I never said that's the way it _should_ have been, I said that's the way it is/was coded in Sloth. You'd have to ask the person who originally did that what their rationale was.

As for the timings, order, and AoE, I'm fixing that. Be patient.

**Closed** 2024-08-23 02:10 UTC
