### ISSUE TITLE
[MCH} Wildfire and Heat Guage

### ISSUE THREAD

**Issue by Tomato619** [Nik-Potokar/XIVSlothCombo#1504] opened 2024-07-11 22:06 UTC
Wildfire issue still persists, doesnt use it after 2 min window. Also refuses to use heat guage past 2:30. Overcaps Heat Guage by A LOT (I assume its cause of the WF issue). Like 2:30 - 4:00ish doesnt use any heat guage.

This was tested in both Everkeep(EX) and Lv 100 Dummy (Stone, Sky, Sea Dummy in solution 9)
Tried both Advanced and Simple.

Thanks as always for the hard work <3

**Comment by Q023** [comment] 2024-07-11 23:35
Can confirm that this issue is also in Worqor Lar Dor Extreme Trial. It just stops using Heat Gauge and Wildfire after the first one.

**Comment by Crowbarx** [comment] 2024-07-12 00:44
What skill speed are you guys at? This was happening to me when I had skill speed gear on and I fixed it by removing pieces that alter my skill speed so i'm back at 2.5.

**Comment by davechopz** [comment] 2024-07-12 04:46
> What skill speed are you guys at? This was happening to me when I had skill speed gear on and I fixed it by removing pieces that alter my skill speed so i'm back at 2.5.

I'm at 2.41 and I have this same exact issue. I'll need to remove some gear and hit a dummy to verify but that might be the problem. 

This has been happening to me much more lately, might have something to do with the most recent update but I can confirm that this does exist! Thanks :D

**Comment by Tomato619** [comment] 2024-07-12 09:54
> What skill speed are you guys at? This was happening to me when I had skill speed gear on and I fixed it by removing pieces that alter my skill speed so i'm back at 2.5.

Even if it does work at 2.5 SKS, its a temporary solution at best, as you would have to remove quite a few pieces to achieve that.

Im sure Kage will find a solution soon enough :)

**Comment by Kagekazu** [comment] 2024-07-12 10:13
It's on my to do for tonight. 

What it should be is : 
- check if u have FMF buff (if u do, cast hypercharge)

- if u don't, check the cooldown of Drill, Air Anchor and Chainsaw if they are longer than the hypercharge window. 

- If they are longer, check if wildfire cooldown is longer than 5gcd's. If that is also longer, cast hypercharge.

- The only check wildfire has atm is the last skill u used is hypercharge. 

Maybe the issue is the doubleweave?

**Comment by Kagekazu** [comment] 2024-07-12 10:15
![image](https://github.com/user-attachments/assets/65d79d63-b619-4b80-ba1a-6a73080a2542)

This is what it should do. So afaik everything is okay positionwise except the WF, which is doubleweaved.

**Comment by elmigo69** [comment] 2024-07-16 20:38
Still have issue with wildfire not being used in single heatblast button and single solo target

**Comment by Kagekazu** [comment] 2024-07-16 20:42
> Still have issue with wildfire not being used in single heatblast button and single solo target

sloth hasnt updated MCH yet, if the link to #1533 ( just above ur comment) is said to Merged it means its on live version of sloth.

**Closed** 2024-07-23 07:22 UTC
