### ISSUE TITLE
[NIN] Request: Armor Crush/Aeolian Edge to Fleeting Raiju 

### ISSUE THREAD

**Issue by bisshmal** [Nik-Potokar/XIVSlothCombo#138] opened 2022-01-16 08:02 UTC
Options to Replace Armor Crush/Aeolian Edge combo with Fleeting Raiju when you have Raiju stacks.

**Comment by Nik-Potokar** [comment] 2022-01-16 09:00
Will add but can you just confirm to me which of this two buffs does it use for raiju
![image](https://user-images.githubusercontent.com/76532587/149653721-2b87e490-9384-41fb-8b97-5ac5826485f4.png)
Since iirc they changed something in last patch (i dont have a lvl90 nin yet)

**Comment by bisshmal** [comment] 2022-01-16 09:20
Yeah awesome! It's the second one.
 [Raiju Ready]
![image](https://user-images.githubusercontent.com/97825110/149654185-49697dd2-9af5-4ecf-929c-c9161ff8c37d.png)

**Comment by Nik-Potokar** [comment] 2022-01-16 09:46
Thanks! Will be added shortly along with the other requested feature

**Comment by Nik-Potokar** [comment] 2022-01-16 10:08
@bisshmal Will be live in a few please give it a test and let me know if it works as intended

**Comment by bisshmal** [comment] 2022-01-16 10:50
@Nik-Potokar Thanks. Everything seems to be working great.

The only thing I would suggest is that "Fleeting Raiju" should always take priority over "Huraiji" since using weaponskills remove "Raiju Ready".

I did notice that the old [Huraijin/Raiju] feature now uses "Fleeting Raiju", previously it was "Forked Raiju". Would be nice to be able to select which one is used. Other than that awesome work. Thanks.

**Comment by Nik-Potokar** [comment] 2022-01-16 11:13
Prio should be fixed now if there are still any issues with it il add another check.

And added options for hura/raiju/forked so now you can choose which one you want on Hura sice both use RaijuReady according to the tooltip.

**Comment by bisshmal** [comment] 2022-01-16 12:05
Working flawlessly. Thanks! Appreciate your work.

**Closed** 2022-01-16 12:05 UTC
