### ISSUE TITLE
[SAM} Adv. mode kenki sliders non-functional

### ISSUE THREAD

**Issue by Whitemoose78** [Nik-Potokar/XIVSlothCombo#1693] opened 2024-08-10 14:26 UTC
The Shinten/Kyuten kenki slider on the adv. ST and AOE combo's seems to be non-functional, and it always dumps any kenki above 50, even with the ikishoten function unticked (which does actually dump kenki below 50 properly as Ikishoten comes off cd).
I've managed to adjust it to my liking by setting it manually in the sam.cs files (lines 438/793), but figured I'd report it here anyways.

**Comment by Kagekazu** [comment] 2024-08-10 20:23
they are fixed in the next release! found the root cause

**Closed** 2024-08-23 02:05 UTC
